### ISSUE TITLE
Match doesn't include entire emoji for some emojis.

### ISSUE THREAD

**Issue by ZDemeter** [mathiasbynens/emoji-regex#35] opened 2018-06-29 11:24 UTC
When matching a string for emojis, the returned match does not include the entire emoji.

For example, 

```js
let emojiString = 'peace hand -> ✌️';
let match = EmojiRegex.exec(emojiString);

console.log(✌️===match[0]); //false
```

Instead match[0] returns
```js
✌
```

The match doesn't include the entire emoji.
An emoji consists of 2 16-bit code points, but for some emojis, only the first code point is matched and returned, giving these weird emojis in browsers.

(A couple of minutes in https://thekevinscott.com/emojis-in-javascript/ , and I can pretend to know anything about emojis 👍 )

**Comment by mathiasbynens** [comment] 2018-08-31 19:40
I cannot reproduce the issue using the latest version:

```js
const emojiRegex = require('emoji-regex');

const string = '\u270C\uFE0F'; // '✌️'
console.log(
	string.match(emojiRegex())
);
// → [ '✌️' ]
```

Closing as fixed.

**Closed by mathiasbynens** 2018-08-31 19:40 UTC
